spring:
  profiles:
    active: "dev"
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8999

flyway:
  locations: classpath:flyway/schema

management:
  contextPath: /actuator

loyalty-program:
  walletGainedPointsPool: 0
  walletGiveAwayPointsPool: 10
  specialPermissionPointsPool: 10
  adminUsername: "admin@sample.com"
  adminPassword: "admin7"
  db:
    samplesPath: ~

tasks:
  resetPoints:
    walletCron: "0 0 1 * * MON"
    specialPermissionCron: "0 0 1 * * *"
  assignBadges:
    memberOfTheYear: "0 0 0 25 12 *"
    memberOfTheMonth: "0 0 0 25 * *"
    memberOfTheDay: "0 0 23 * * *"