spring:
  datasource:
      url: jdbc:mysql://localhost:3306/loyalty_program?useSSL=true
      username: be
      password: loyal
  jpa:
    hibernate:
      ddl-auto: create

security:
  oauth2:
    client:
      clientId: <GOOGLE_CLIENT_ID>
      clientSecret: <GOOGLE_CLIENT_SECRET>
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope:
        - openid
        - email
        - profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true