spring:
  profiles:
    active: "dev"
  jackson:
    serialization:
      write-dates-as-timestamps: false
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8999

flyway:
  locations: classpath:flyway

management:
  contextPath: /actuator

loyalty-program:
  initial-gained-points-pool: 0
  initial-give-away-points-pool: 10