spring:
  datasource:
    url: jdbc:h2:mem:loyalty_program;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    platform: h2
  h2:
    console:
      enabled: true
      path: /h2-console