spring:
  profiles:
    active: "dev"
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8999
  
flyway:
  locations: classpath:flyway

---

spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:loyalty_program;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    platform: h2
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console

---

spring:
  profiles: prod
  datasource:
      url: jdbc:mysql://localhost:3306/loyalty_program
      username: be
      password: loyal
  jpa:
    hibernate:
      ddl-auto: create
